#!/bin/sh
# $Id: pdf2eps,v 0.01 2005/10/28 00:55:46 Herbert Voss Exp $
# pdf2eps Shell script by SyneArt <sa@syneart.com> 2017/08/28
# Convert PDF to encapsulated PostScript.
# usage:
# pdf2eps.sh <page number> <pdf file>

usage () {
    echo "Usage: pdf2eps.sh <page number> <pdf file>"
}

#if [ "$1/" == "/" ]; then usage; exit; fi
#if [ "$2/" == "/" ]; then usage; exit; fi

# remove ext
#ORIGINAL_PDF_FILE="${2%.[^.]*}"
echo $2
pdfcrop "$2.pdf"
pdftops -f $1 -l $1 -eps "$2-crop.pdf"
echo "==> Creating output file $2.eps."
rm "$2-crop.pdf"
mv "$2-crop.eps" "$2.eps"
exit 0
